In [313]:
import pandas as pd

In [314]:
#Series (Single Column)
cgpa = pd.Series([8.2,7.4,9.1])
cgpa

0    8.2
1    7.4
2    9.1
dtype: float64

In [315]:
#DataFrame (Multiple Columns)
df = pd.DataFrame({
    "Name" : ["Alice", "Bob", "John"],
    "CGPA" : [8.2, 7.4, 9.1],
    "Package" : [12, 8, 18]
})

In [316]:
df

    Name  CGPA  Package
0  Alice   8.2       12
1    Bob   7.4        8
2   John   9.1       18

In [317]:
df["CGPA"]

0    8.2
1    7.4
2    9.1
Name: CGPA, dtype: float64

In [318]:
df[df["CGPA"] > 8]

    Name  CGPA  Package
0  Alice   8.2       12
2   John   9.1       18

In [319]:
students = pd.Series(
    [8.9, 7.5, 9.1],
    index=["Alice", "Bob", "Charlie"]
)

df

    Name  CGPA  Package
0  Alice   8.2       12
1    Bob   7.4        8
2   John   9.1       18

In [320]:
students["Bob"]

np.float64(7.5)

In [321]:
#Reading and Inspecting Data
df = pd.read_csv("/kaggle/input/datasets/somya2115/placement-csv/placement.csv")

In [322]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [323]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [324]:
df.head(10)

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0
5           5   7.1   48.0          1
6           6   5.7  143.0          0
7           7   5.0   63.0          0
8           8   6.1  156.0          0
9           9   5.1   66.0          0

In [325]:
df.tail()

    Unnamed: 0  cgpa     iq  placement
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

In [326]:
df.sample(5) #Random data

    Unnamed: 0  cgpa     iq  placement
38          38   6.5  160.0          1
2            2   5.3  121.0          0
14          14   6.1  103.0          0
67          67   5.0  118.0          0
50          50   3.5  233.0          0

In [327]:
df.shape

(100, 4)

In [328]:
df.columns

Index(['Unnamed: 0', 'cgpa', 'iq', 'placement'], dtype='object')

In [329]:
df.dtypes

Unnamed: 0      int64
cgpa          float64
iq            float64
placement       int64
dtype: object

In [330]:
df.info() #Very used

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

In [331]:
df.describe()

       Unnamed: 0        cgpa          iq   placement
count  100.000000  100.000000  100.000000  100.000000
mean    49.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      0.000000    3.300000   37.000000    0.000000
25%     24.750000    5.075000  101.500000    0.000000
50%     49.500000    6.000000  127.500000    0.500000
75%     74.250000    6.900000  149.000000    1.000000
max     99.000000    8.500000  233.000000    1.000000

In [332]:
df.isnull().sum() #By this, missing datas can be identified

Unnamed: 0    0
cgpa          0
iq            0
placement     0
dtype: int64

In [333]:
# ==========================================
# Dataset Inspection Checklist
# ==========================================

# Display the first 5 rows of the dataset
# df.head()

# Display the last 5 rows of the dataset
# df.tail()

# Display 5 random rows from the dataset
# df.sample(5)

# Display the shape of the dataset
# Output: (number_of_rows, number_of_columns)
# df.shape

# Display all column names
# df.columns

# Display the data type of each column
# df.dtypes

# Display complete dataset information
# Includes:
# - Number of rows
# - Number of columns
# - Non-null values
# - Data types
# - Memory usage
# df.info()

# Display statistical summary of numerical columns
# Includes:
# - Count
# - Mean
# - Standard Deviation
# - Minimum
# - 25th Percentile
# - Median (50%)
# - 75th Percentile
# - Maximum
# df.describe()

# Display the total number of missing (NaN) values in each column
# df.isnull().sum()

# Display the total number of duplicate rows
# df.duplicated().sum()

# ==========================================
# Categorical Column Inspection
# (Replace "column_name" with an actual column)
# ==========================================

# Display all unique values in a column
# Example:
# df["gender"].unique()

# Display the total number of unique values
# Example:
# df["gender"].nunique()

# Display the frequency of each unique value
# Example:
# Male      120
# Female     80
# df["column_name"].value_counts()

In [334]:
#Selecting Data (COLUMNS)

In [335]:
df["cgpa"]

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

In [336]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [337]:
df[["cgpa", "iq"]]

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

In [338]:
#Selecting Data (ROWS)

In [339]:
df.iloc[0] #iloc = Integer Location

Unnamed: 0      0.0
cgpa            6.8
iq            123.0
placement       1.0
Name: 0, dtype: float64

In [340]:
df.iloc[1]

Unnamed: 0      1.0
cgpa            5.9
iq            106.0
placement       0.0
Name: 1, dtype: float64

In [341]:
df.iloc[:3] #First 3 Rows

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0

In [342]:
#Selecting Rows and Columns

In [343]:
df.iloc[:3, 1] #First 3 rows only CGPA

0    6.8
1    5.9
2    5.3
Name: cgpa, dtype: float64

In [344]:
df.iloc[:5,[1,2]] #First 5 rows, CGPA and IQ

   cgpa     iq
0   6.8  123.0
1   5.9  106.0
2   5.3  121.0
3   7.4  132.0
4   5.8  142.0

In [345]:
#Boolean Indexing

In [346]:
df[df["cgpa"] > 8]

    Unnamed: 0  cgpa     iq  placement
37          37   8.1  149.0          1
53          53   8.3  168.0          1
65          65   8.1  166.0          1
69          69   8.5  120.0          1

In [347]:
df[
(df["cgpa"] > 8) & (df["iq"] > 150)
]

    Unnamed: 0  cgpa     iq  placement
53          53   8.3  168.0          1
65          65   8.1  166.0          1

In [348]:
#Sorting

In [349]:
df.sort_values("cgpa")

    Unnamed: 0  cgpa     iq  placement
17          17   3.3  183.0          0
50          50   3.5  233.0          0
31          31   3.9  109.0          0
18          18   4.0  100.0          0
68          68   4.0   75.0          0
..         ...   ...    ...        ...
58          58   8.0   79.0          1
65          65   8.1  166.0          1
37          37   8.1  149.0          1
53          53   8.3  168.0          1
69          69   8.5  120.0          1

[100 rows x 4 columns]

In [350]:
df.sort_values("cgpa", ascending=False)

    Unnamed: 0  cgpa     iq  placement
69          69   8.5  120.0          1
53          53   8.3  168.0          1
37          37   8.1  149.0          1
65          65   8.1  166.0          1
58          58   8.0   79.0          1
..         ...   ...    ...        ...
18          18   4.0  100.0          0
68          68   4.0   75.0          0
31          31   3.9  109.0          0
50          50   3.5  233.0          0
17          17   3.3  183.0          0

[100 rows x 4 columns]

In [351]:
#Unique Values

In [352]:
df["cgpa"].unique()

array([6.8, 5.9, 5.3, 7.4, 5.8, 7.1, 5.7, 5. , 6.1, 5.1, 6. , 6.9, 5.4,
       6.4, 5.2, 3.3, 4. , 6.6, 4.9, 4.7, 7. , 7.6, 3.9, 4.8, 8.1, 6.5,
       4.6, 7.5, 3.5, 8.3, 7.8, 8. , 7.3, 6.3, 8.5, 6.7, 4.4, 4.3, 6.2])

In [353]:
df["cgpa"].nunique() #Total number of UNIQUE

39

In [354]:
df["cgpa"].value_counts()

cgpa
4.9    6
6.1    5
5.2    5
6.0    5
7.0    5
5.7    4
6.8    4
7.3    4
5.4    4
6.5    4
4.8    4
7.5    3
4.7    3
5.1    3
6.3    3
5.0    3
6.9    3
4.0    2
7.1    2
5.3    2
4.4    2
5.8    2
6.4    2
6.7    2
8.1    2
6.6    2
7.6    2
7.4    1
5.9    1
3.9    1
3.3    1
7.8    1
8.3    1
3.5    1
4.6    1
8.5    1
8.0    1
4.3    1
6.2    1
Name: count, dtype: int64

In [355]:
df[["cgpa"]] #DataFrame

    cgpa
0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
..   ...
95   4.3
96   4.4
97   6.7
98   6.3
99   6.2

[100 rows x 1 columns]

In [356]:
df["cgpa"] #Series

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

In [357]:
#Data Cleaning

In [358]:
df.isnull().sum()

Unnamed: 0    0
cgpa          0
iq            0
placement     0
dtype: int64

In [359]:
df.dropna() #Removes rows that have missing values

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [360]:
df.fillna(0) #Fill with 0's

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [361]:
#Fill with the Mean

In [362]:
df["cgpa"] = df["cgpa"].fillna(df["cgpa"].mean())

In [363]:
#Fill with the Most Frequent Value

In [364]:
df["cgpa"] = df["cgpa"].fillna(df["cgpa"].mode()[0])

In [365]:
#Duplicated Rows

In [366]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [367]:
df.duplicated().sum()

np.int64(0)

In [368]:
df.drop_duplicates()

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [369]:
#Changing Data Type

In [370]:
df["cgpa"] = df["cgpa"].astype(int)

In [371]:
#Data Transformation and Feature Engineering

In [372]:
performance_df = pd.read_csv("/kaggle/input/datasets/devansodariya/student-performance-data/student_data.csv")

In [373]:
performance_df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [374]:
df2 = performance_df

df2[["age"]]

     age
0     18
1     17
2     15
3     15
4     16
..   ...
390   20
391   17
392   21
393   18
394   19

[395 rows x 1 columns]

In [375]:
#df2[["Age after 5 years"]] #Feature Engineering

In [376]:
#df2[["age", "Age after 5 years"]]

In [377]:
df2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [378]:
df

    Unnamed: 0  cgpa     iq  placement
0            0     6  123.0          1
1            1     5  106.0          0
2            2     5  121.0          0
3            3     7  132.0          1
4            4     5  142.0          0
..         ...   ...    ...        ...
95          95     4  200.0          0
96          96     4   42.0          0
97          97     6  182.0          1
98          98     6  103.0          1
99          99     6  113.0          1

[100 rows x 4 columns]

In [379]:
#Arithmetic Operations

In [380]:
df["iq"] = df["iq"] * 1.10
df[["iq"]]

       iq
0   135.3
1   116.6
2   133.1
3   145.2
4   156.2
..    ...
95  220.0
96   46.2
97  200.2
98  113.3
99  124.3

[100 rows x 1 columns]

In [381]:
#apply()

In [382]:
def grade(cgpa):
    if cgpa >= 8:
        return "Excellent"
    elif cgpa >= 7:
        return "Good"
    else:
        return "Average"

df["Performance"] = df["cgpa"].apply(grade)

In [383]:
df[["cgpa","Performance"]]

    cgpa Performance
0      6     Average
1      5     Average
2      5     Average
3      7        Good
4      5     Average
..   ...         ...
95     4     Average
96     4     Average
97     6     Average
98     6     Average
99     6     Average

[100 rows x 2 columns]

In [384]:
#where

df2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [385]:
df2["Age Group"] = pd.cut(
    df2["age"],
    bins=[0,20,35,100],
    labels=["Young","Adult","Senior"]
)

In [386]:
df2[["age", "Age Group"]]

     age Age Group
0     18     Young
1     17     Young
2     15     Young
3     15     Young
4     16     Young
..   ...       ...
390   20     Young
391   17     Young
392   21     Adult
393   18     Young
394   19     Young

[395 rows x 2 columns]

In [387]:
#GroupBy and Aggregation

In [388]:
df2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,Age Group
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,Young
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,Young
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,Young
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,Young
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,4,5,4,11,9,9,9,Young
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,3,14,16,16,Young
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,3,3,3,3,3,10,8,7,Adult
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,0,11,12,10,Young
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,2,3,3,3,5,5,8,9,9,Young

In [389]:
df2.groupby("school")[["age"]].mean()

              age
school
GP      16.521490
MS      18.021739

In [390]:
df2.groupby("school")[["age"]].count()

        age
school
GP      349
MS       46

In [391]:
df2.groupby("school")[["age"]].max()

        age
school
GP       22
MS       21

In [392]:
df2.groupby("school")[["age"]].sum()

         age
school
GP      5766
MS       829

In [393]:
df2.groupby("school")[["age"]].median()

         age
school
GP      16.0
MS      18.0

# EDA, Data Cleaning, Preprocessing with Pandas

## EDA with Pandas

In [394]:
import pandas as pd
df = pd.read_csv("/kaggle/input/competitions/titanic/train.csv")

In [395]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [396]:
df.shape

(891, 12)

In [397]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [398]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [399]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [400]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [401]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [402]:
df.isnull().sum().sort_values(ascending = False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

In [403]:
df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [404]:
df["Sex"].value_counts(normalize=True)

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [405]:
df["Age"].median()

28.0

In [406]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [407]:
df.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [408]:
df.groupby("Sex")["Survived"].agg(["count", "sum", "mean"])

        count  sum      mean
Sex
female    314  233  0.742038
male      577  109  0.188908

In [409]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
424,425,0,3,"Rosblom, Mr. Viktor Richard",male,18.0,1,1,370129,20.2125,NaN,S
396,397,0,3,"Olsson, Miss. Elina",female,31.0,0,0,350407,7.8542,NaN,S
145,146,0,2,"Nicholls, Mr. Joseph Charles",male,19.0,1,1,C.A. 33112,36.7500,NaN,S
123,124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13.0000,E101,S
583,584,0,1,"Ross, Mr. John Hugo",male,36.0,0,0,13049,40.1250,A10,C

In [410]:
df.groupby("Pclass")[["Survived"]].mean()

        Survived
Pclass
1       0.629630
2       0.472826
3       0.242363

In [411]:
df.groupby(["Sex", "Pclass"])[["Survived"]].mean()

               Survived
Sex    Pclass
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

In [412]:
df.groupby("Embarked")["Survived"].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [413]:
pd.crosstab(df["Embarked"], df["Pclass"])

Pclass      1    2    3
Embarked
C          85   17   66
Q           2    3   72
S         127  164  353

In [414]:
pd.crosstab(
    df["Embarked"],
    df["Pclass"],
    normalize="index"
) * 100

Pclass            1          2          3
Embarked
C         50.595238  10.119048  39.285714
Q          2.597403   3.896104  93.506494
S         19.720497  25.465839  54.813665

In [415]:
pd.crosstab(
    [df["Embarked"], df["Pclass"]],
    df["Survived"],
    normalize="index"
) * 100

Survived                 0          1
Embarked Pclass
C        1       30.588235  69.411765
         2       47.058824  52.941176
         3       62.121212  37.878788
Q        1       50.000000  50.000000
         2       33.333333  66.666667
         3       62.500000  37.500000
S        1       41.732283  58.267717
         2       53.658537  46.341463
         3       81.019830  18.980170

In [416]:
df["Pclass"].unique()

array([3, 1, 2])

In [417]:
df[["Name", "Age", "Fare"]]

                                                  Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                               Heikkinen, Miss. Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
886                              Montvila, Rev. Juozas  27.0  13.0000
887                       Graham, Miss. Margaret Edith  19.0  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  23.4500
889                              Behr, Mr. Karl Howell  26.0  30.0000
890                                Dooley, Mr. Patrick  32.0   7.7500

[891 rows x 3 columns]

In [418]:
df[df["Pclass"] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [419]:
df[(df["Pclass"]==1) & (df["Survived"]==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [420]:
df.iloc[0:5, 3:7]  #[rows, columns]

                                                Name     Sex   Age  SibSp
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

In [421]:
df.sort_values("Fare", ascending=False).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S

In [422]:
df[["Name", "Sex", "Age", "Survived"]]

                                                  Name     Sex   Age  Survived
0                              Braund, Mr. Owen Harris    male  22.0         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                               Heikkinen, Miss. Laina  female  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                             Allen, Mr. William Henry    male  35.0         0
..                                                 ...     ...   ...       ...
886                              Montvila, Rev. Juozas    male  27.0         0
887                       Graham, Miss. Margaret Edith  female  19.0         1
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN         0
889                              Behr, Mr. Karl Howell    male  26.0         1
890                                Dooley, Mr. Patrick    male  32.0         0

[891 rows x 4 columns]

In [423]:
df[(df["Age"] < 18) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

In [424]:
df.sort_values("Fare", ascending=False).tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S

In [425]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [426]:
df.isnull().mean()*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [427]:
df.duplicated().sum()

np.int64(0)

In [428]:
df[df["Embarked"].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [429]:
df[df["Age"].isnull()].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

In [430]:
(df["Age"].isnull() & df["Cabin"].isnull()).sum()

np.int64(158)

In [431]:
df["Age"].mean()

np.float64(29.69911764705882)

In [432]:
df["Age"].median()

28.0

In [433]:
df["Age"].skew()

np.float64(0.38910778230082704)

In [434]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [435]:
df["Age"].isnull().sum()

np.int64(0)

In [436]:
df["Age"].mean()

np.float64(29.36158249158249)

In [437]:
df = df.drop(columns=["Cabin"])

In [438]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [439]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [440]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [441]:
df["Embarked"].mode()

0    S
Name: Embarked, dtype: object

In [442]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [443]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [444]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [445]:
df["Sex"] = df["Sex"].astype("category")
df["Pclass"] = df["Pclass"].astype("category")
df["Embarked"] = df["Embarked"].astype("category")

df["Survived"] = df["Survived"].astype("int32")
df[["SibSp", "Parch"]] = df[["SibSp", "Parch"]].astype("int32")

In [446]:
df[["SibSp", "Parch"]].dtypes

SibSp    int32
Parch    int32
dtype: object

In [447]:
df[["Age", "Fare", "SibSp", "Parch"]].dtypes

Age      float64
Fare     float64
SibSp      int32
Parch      int32
dtype: object

In [448]:
Numbers = ["7.25", "6.54", "9.54"]

Numbers = pd.to_numeric(Numbers)

In [449]:
Numbers.mean()

np.float64(7.776666666666666)

In [450]:
df["Sex"] = df["Sex"].replace({
    "male" : "M",
    "female" : "F"
})

/tmp/ipykernel_58/4281890000.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["Sex"] = df["Sex"].replace({

In [451]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.0500,S

In [452]:
df["Sex"] = df["Sex"].replace({
    "M" : "male",
    "F" : "female"
})

/tmp/ipykernel_58/1697441779.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["Sex"] = df["Sex"].replace({

In [453]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [454]:
test = pd.DataFrame({
    "City" : ["Chittagong", "CTG", "Dhaka", "DHK"]
})

print(test["City"].value_counts())

test["City"] = test["City"].replace({
    "Chittagong" : "CTG",
    "Dhaka" : "DHK"
})
print()
print(test["City"].value_counts())

City
Chittagong    1
CTG           1
Dhaka         1
DHK           1
Name: count, dtype: int64

City
CTG    2
DHK    2
Name: count, dtype: int64

In [455]:
df.rename(columns={
    "SibSp" : "SiblingsSpouses",
    "Parch" : "ParentsChildren"
}, inplace=True)

In [456]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SiblingsSpouses', 'ParentsChildren', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [457]:
df.rename(columns={
    "SiblingsSpouses" : "SibSp",
    "ParentsChildren" : "Parch"
}, inplace=True)

In [458]:
test = pd.Series(["Male", "MALE", "male", "Female", "FEMALE"])

print(test.value_counts())

Male      1
MALE      1
male      1
Female    1
FEMALE    1
Name: count, dtype: int64

In [459]:
test = test.str.lower()      #upper(), title()
print(test.value_counts())

male      3
female    2
Name: count, dtype: int64

In [460]:
import pandas as pd


test = pd.DataFrame({
    'book_titles': ['the great gatsby', 'to kill a mockingbird', 'they\'re watching you']})

test['book_titles'] = test['book_titles'].str.title()
print(test)

             book_titles
0       The Great Gatsby
1  To Kill A Mockingbird
2   They'Re Watching You

In [461]:
df["Name"].str.contains("Mr").sum()

np.int64(647)

# Feature Creation

In [462]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

In [463]:
df = df.drop(columns=["SibSp", "Parch"])

In [464]:
df.groupby("FamilySize")["Survived"].agg(
    ["count", "mean"]
)

            count      mean
FamilySize
1             537  0.303538
2             161  0.552795
3             102  0.578431
4              29  0.724138
5              15  0.200000
6              22  0.136364
7              12  0.333333
8               6  0.000000
11              7  0.000000

In [465]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,S,1